/* Autogenerated by png2wx.pl on Tue Sep  8 15:53:52 2020 */
#ifndef ICONS_H
#define ICONS_H 1
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif
extern void initialize_images(void);
extern wxBitmap *_img_odometer;
extern wxBitmap *_img_odometer_colour;
extern wxBitmap *_img_odometer_rollover;
extern wxBitmap *_img_odometer_toggled;

#endif /* ICONS_H */
